name: Linux C++11
on:
  push:
    branches: [ "v3" ]
env:
  GCC_VERSION: 11
jobs:
  build_matrix:
    strategy:
      matrix:
        clang: [ 13, 14, 15, 16, 17 ]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: .xmake-cache
        key: xmake-cache-${{ runner.os }}
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: .xmake-cache
    - if: matrix.clang == 16
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0.6"
    - if: matrix.clang == 17
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17.0.6"
    - name: Build
      run: CLANG_VERSION=${{ matrix.clang }} xmake build -w -v "Tests cxx11"
    - name: Test
      run: CLANG_VERSION=${{ matrix.clang }} xmake run "Tests cxx11"
