name: Linux C++11
on:
  push:
    branches: [ "v3" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xmake build -w -v "Tests cxx11"
    - name: Test
      run: xmake run "Tests cxx11"
